// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuudbrjcipsolnwbohil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dWRicmpjaXBzb2xud2JvaGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTU3NDUsImV4cCI6MjA2NTg5MTc0NX0.sHFrakswru-VbW2CO-dasw_YNRyG7PxQrZLx9GAZtKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);